##############################path##############################
SCE_PATH = '.\\img\\sce\\'
SOG_PATH = '.\\img\\sog\\'
DEF_PATH = '.\\img\\def\\'
WAR_PATH = '.\\img\\war\\'
EXP_PATH = '.\\img\\exp\\'
MIT_PATH = '.\\img\\mit\\'
TSK_PATH = '.\\img\\tsk\\'
##############################img##############################
IMG_SCROLL_ON = SCE_PATH + 'scroll_on.png'
IMG_SCENE = SCE_PATH + 'scene_1.png'
IMG_SCENE_EARTHLY = SCE_PATH + 'earthly.png'
IMG_SCENE_ESC = SCE_PATH + 'esc.png'
IMG_BUFF = SCE_PATH + 'buff.png'
IMG_BUFF_BUTTON = SCE_PATH + 'buff_button.png'
IMG_SCROLL_OFF = SCE_PATH + 'scroll_off.png'
IMG_SCROLL_ONALL = SCE_PATH + 'scroll_onall.png'
IMG_SHIKIGAMI = SCE_PATH + 'shikigami.png'
IMG_SELF = SCE_PATH + 'self.png'
IMG_DEFENDER_0 = SCE_PATH + 'defender_0.png'
IMG_PRESET_0 = SCE_PATH + 'preset_0.png'
IMG_PRESET_1 = SCE_PATH + 'preset_1.png'
IMG_PRESET_2 = SCE_PATH + 'preset_2.png'
IMG_PRESET_4 = SCE_PATH + 'preset_4.png'
IMG_PRESET_5 = SCE_PATH + 'preset_5.png'
IMG_FIGHT_PREPARE = SCE_PATH + 'prepare.png'
IMG_FIGHT_ENTER = SCE_PATH + 'enter.png'
IMG_GUILD = SCE_PATH + 'guild.png'
IMG_GUILD_IN = SCE_PATH + 'guild_in.png'
IMG_TEAM_MAKE = SCE_PATH + 'team_0.png'
IMG_TEAM_INTERFACE = SCE_PATH + 'team_interface.png'
IMG_TEAM_IN = SCE_PATH + 'team_in.png'
IMG_TEAM_A = SCE_PATH + 'team_awaken.png'
IMG_TEAM_E = SCE_PATH + 'team_explore.png'
IMG_TEAM_M = SCE_PATH + 'team_mitama.png'
IMG_TEAM_S = SCE_PATH + 'team_sunwheel.png'
IMG_TEAM_ADD = SCE_PATH + 'team_add.png'
IMG_TEAM_FEIEND = SCE_PATH + 'team_friend.png'
IMG_TEAM_SCENE = SCE_PATH + 'team_scene.png'
IMG_REFUSE = TSK_PATH + 'refuse.png'
IMG_TASKS = TSK_PATH + 'tasks.png'
IMG_SGF_LV3 = SOG_PATH + 'lv3.png'
IMG_SGF_FIGHT = SOG_PATH + 'fight.png'
IMG_SGF_WIN = SOG_PATH + 'win.png'
IMG_DEF_LV3 = DEF_PATH + 'lv3.png'
IMG_DEF_FIGHT = DEF_PATH + 'fight.png'
IMG_DEF_WIN = DEF_PATH + 'win.png'
IMG_FIGHT_QUIT = WAR_PATH + 'quit.png'
IMG_WAR_FIGHT = WAR_PATH + 'fight_1.png'
IMG_WAR_QUIR_CONFIRM = WAR_PATH + 'affirm_quit.png'
IMG_WAR_REFRESH_CONFIRM = WAR_PATH + 'affirm_refresh.png'
IMG_WAR_SUCCEED = WAR_PATH + 'warded.png'
IMG_FIGHT_FAIL = WAR_PATH + 'fail.png'
IMG_WARD_IN = WAR_PATH + 'ward_in.png'
IMG_WAR_REFRESH = WAR_PATH + 'refresh.png'
IMG_FIGHT_WIN = WAR_PATH + 'win.png'
IMG_WAR_LIAO = WAR_PATH + 'liao.png'
IMG_WAR_END = WAR_PATH + 'end.png'
IMG_WAR_RUNOUT_SINGLE = WAR_PATH + 'runout_0.png'
IMG_WAR_RUNOUT_GUILD = WAR_PATH + 'runout_1.png'
IMG_WAR_COOLDOWN = WAR_PATH + 'cooldown.png'
IMG_WRD_MEDAL = WAR_PATH + 'medal.png'
IMG_MIT_FIGHT = MIT_PATH + 'fight.png'
IMG_MIT_WIN   = MIT_PATH + 'win.png'
IMG_MIT_QUIT  = MIT_PATH + 'quit.png'
IMG_MIT_COUNT  = MIT_PATH + 'count.png'
IMG_MIT_ACCEPT  = MIT_PATH + 'multi_accept.png'
IMG_MIT_ALWAYS  = MIT_PATH + 'multi_always.png'
IMG_TEAM_CREAT = MIT_PATH + 'multi_team_2.png'
IMG_TEAM_INVITE_INTERFACE = MIT_PATH + 'multi_team_3.png'
ING_MIT_5 = MIT_PATH + 'multi_team_5.png'
IMG_EXP_ROTATE = EXP_PATH + 'rotate.png'
IMG_TEAM_ADD = EXP_PATH + 'creat_1.png'
IMG_TEAM_FRIEND_LOCAL = EXP_PATH + 'creat_2.png'
IMG_TEAM_FRIEND_TRANS = EXP_PATH + 'creat_2_0.png'
IMG_TEAM_FRIEND_INVITED = EXP_PATH + 'creat_4.png'
IMG_TEAM_INVITE = EXP_PATH + 'creat_5.png'
IMG_EXP_QUIT = EXP_PATH + 'quit_2.png'
IMG_EXP_AUTO = EXP_PATH + 'auto.png'
IMG_EXP_QUIT_CONFIRM = EXP_PATH + 'quit_3.png'
IMG_EXP_INVITED = EXP_PATH + 'invited.png'
IMG_EXP_ACCEPT = EXP_PATH + 'accept.png'
IMG_EXP_FIGHT = EXP_PATH + 'fight.png'
IMG_EXP_X = EXP_PATH + 'x.png'
IMG_EXP_XX = EXP_PATH + 'xx.png'
IMG_EXP_CONTINUE = EXP_PATH + 'continue.png'
IMG_EXP_PAUSE = EXP_PATH + 'pause.png'
IMG_EXP_INTERFACE = EXP_PATH + 'in_explore.png'
##############################loc##############################
# loc_enter_explore = {'C': (560,60), 'R': (18,18)}
LOC_EXP_ENTER = {'C': (325,58), 'R': (24,24)}
LOC_DEF_BLANK = {'C': (195,270), 'R': (260,35)} 
LOC_FIGHT_SIGN = {'C': (475,197), 'R': (28,44)}
LOC_FIGHT_PREPARE = {'C': (568,228), 'R': (47,39)}
LOC_TASK_REFUSE = {'C': (377,48), 'R': (14,14)}
LOC_DEF = {}
LOC_DEF[0] = {'C': (104,86), 'R': (51,22)}
LOC_DEF[1] = {'C': (229,86), 'R': (51,22)}
LOC_DEF[2] = {'C': (361,86), 'R': (51,22)}
LOC_DEF[3] = {'C': (485,86), 'R': (51,22)}
LOC_PRESET_GROUP = {}
LOC_PRESET_GROUP[1] = {'C': (531,47), 'R': (46,12)}
LOC_PRESET_GROUP[2] = {'C': (531,77), 'R': (46,12)}
LOC_PRESET_GROUP[3] = {'C': (531,107), 'R': (46,12)}
LOC_PRESET_GROUP[4] = {'C': (531,137), 'R': (46,12)}
LOC_PRESET_NUMBER = {}
LOC_PRESET_NUMBER[1] = {'C': (470,69), 'R': (9,9)}
LOC_PRESET_NUMBER[2] = {'C': (470,136), 'R': (9,9)}
LOC_PRESET_NUMBER[3] = {'C': (470,203), 'R': (9,9)}
LOC_PRESET_NUMBER[4] = {'C': (470,270), 'R': (9,5)}
LOC_SGF_BLANK = {'C': (195,270), 'R': (260,35)} 
LOC_WAR_SINGLE_BLANK = {'C': (195,305), 'R': (360,10)}
LOC_WAR_GUILD_BLANK = {'C': (565,52), 'R': (14,14)}
LOC_WAR_GUILE_CHOOSE = {'C':[270,70], 'R': (70, 45)}
LOC_MITAMA_BLANK = {'C': (400,280), 'R': (230,35)}
LOC_TEAM_CREAT = {'C': (485,270), 'R': (56,16)}
LOC_TEAM_PRIVATE = {'C': (372,222), 'R': (8,8)}
LOC_TEAM_MAKE_6 = {'C': (279,155), 'R': (12,10)}
LOC_TEAM_MAKE_7 = {'C': (13,10), 'R': (16,14)}
LOC_EXP_ROTATE = {'C':(53,294),'R': (9,9)}
LOC_TEAM_FIREDN_FIRST = {'C':(219,90),'R': (91,21)}
LOC_EXP_BLANK = {'C':(441,210),'R': (190,52)}
LOC_TEAM_CHPYER = {'C':(220,230),'R': (66,16)}
##############################drag_loc##############################
DRAG_RANDOM = {'C':(80,80),'R': (480,160)}
DRAG_EXP_RIGHT = {'C':(513,46),'R': (124,64)}
DRAG_EXP_LEFT = {'C':(0,72),'R': (80,205)}
DRAG_TEAM_TOP = {'C':(107,163),'R': (85,29)}
DRAG_TEAM_BOT = {'C':(107,263),'R': (85,29)}
DRAG_TEAM_CHAPTER_TOP = {'C':(220,87),'R': (67,17)}
DRAG_TEAM_CHAPTER_BOT = {'C':(220,227),'R': (67,17)}
##############################region_loc##############################
REGION_UPPER_LEFT = {'C':(0,0),'R': (150,100)}
REGION_WAR_GUILD_END = {'C':(319,55),'R': (53,53)}
REGION_EXP_AUTO = {'C':(0,271),'R': (50,50)}
